
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from './schema';

// Updated to use direct values since process.env is not available in browser context
const SUPABASE_URL = "https://ravfxsqfccftbdaqefvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdmZ4c3FmY2NmdGJkYXFlZnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTUwNzMsImV4cCI6MjA1ODA3MTA3M30.m-oomY_UcqznlIVCSNoCckxHqD_JeYeXNNrjnfJavu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add debugging info to verify connection
console.log("Supabase client initialized with URL:", SUPABASE_URL);
