// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqwvovfezjjlrnvtapmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxd3ZvdmZlempqbHJudnRhcG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzkxNDYsImV4cCI6MjA1NzUxNTE0Nn0.48eFh1F3nODzJ0_iZ8-FQrKmXUnCJVrYg7Yh6HNPxs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);